
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\xd1\x19\xb4S\x1e\xcb\xfa\xec\xa3\xda/Q\x00\x1d\x17-'
    
_lr_action_items = {'WARTOSC_W_CUDZYSLOWIE':([14,],[17,]),'=':([10,],[14,]),'RODZAJ_PUBLIKACJI':([0,1,3,5,13,],[2,-1,2,-2,-3,]),',':([7,9,11,15,16,17,],[8,12,-4,-5,-7,-6,]),'WARTOSC':([6,8,12,14,],[7,10,10,16,]),'{':([2,4,],[-8,6,]),'}':([9,11,15,16,17,],[13,-4,-5,-7,-6,]),'$end':([1,3,5,13,],[-1,0,-2,-3,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'field':([8,12,],[11,15,]),'fields':([8,],[9,]),'type':([0,3,],[4,4,]),'publications':([0,],[3,]),'publication':([0,3,],[1,5,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> publications","S'",1,None,None,None),
  ('publications -> publication','publications',1,'p_publications1','salamon.py',43),
  ('publications -> publications publication','publications',2,'p_publications2','salamon.py',46),
  ('publication -> type { WARTOSC , fields }','publication',6,'p_publication','salamon.py',49),
  ('fields -> field','fields',1,'p_fields1','salamon.py',53),
  ('fields -> fields , field','fields',3,'p_fields2','salamon.py',58),
  ('field -> WARTOSC = WARTOSC_W_CUDZYSLOWIE','field',3,'p_field1','salamon.py',65),
  ('field -> WARTOSC = WARTOSC','field',3,'p_field2','salamon.py',69),
  ('type -> RODZAJ_PUBLIKACJI','type',1,'p_type','salamon.py',73),
]
